# TABUADA — Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.

n1 = int(input('Digite um número inteiro para ver sua tabuada: '))
print('A tabuada de {} é:\n'.format(n1))
print('=' * 15)
print('{} * 1 = {}'.format(n1, n1))
print('{} * 2 = {}'.format(n1, n1 * 2))
print('{} * 3 = {}'.format(n1, n1 * 3))
print('{} * 4 = {}'.format(n1, n1 * 4))
print('{} * 5 = {}'.format(n1, n1 * 5))
print('{} * 6 = {}'.format(n1, n1 * 6))
print('{} * 7 = {}'.format(n1, n1 * 7))
print('{} * 8 = {}'.format(n1, n1 * 8))
print('{} * 9 = {}'.format(n1, n1 * 9))
print('{} * 10 = {}'.format(n1, n1 * 10))
print('=' * 15)
